site_name: spacytextblob
site_description: A TextBlob sentiment analysis pipeline compponent for spaCy.
repo_url: https://github.com/samedwardes/spacytextblob
repo_name: 'samedwardes/spacytextblob'
edit_uri: ''

theme:
  name: material
  logo: static/img/logo_transparent_computer.png
  favicon: static/img/favicon.png
  features:
    - search.suggest
    - search.highlight
    - content.code.annotate

markdown_extensions:
  - mdx_include
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

plugins:
  - search
  - include-markdown

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/samedwardes/spacytextblob
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/therealsamlam
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/samedwardes

nav:
  - Home: 'index.md'
  - getting_started.md
  - textblob_extensions.md
  - Examples:
    - examples/example.md