# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest

on:
  pull_request:
    branches: [ main ]
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry export --without-hashes --output requirements.txt
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        python -m textblob.download_corpora
        python -m spacy download en_core_web_sm
        pip install pytest
    - name: Test with pytest
      run: |
        pytest
